'use client';

import { useEffect, useState } from 'react';
import { ClipboardList } from 'lucide-react';
import AdminAuthGate from '@/components/AdminAuthGate';

interface Order { id: string; orderNumber: string; customerName: string; customerEmail: string; customerPhone: string; status: string; total: number; paymentMethod: string; createdAt: string; shippingAddress: { addressLine1?: string; city?: string; district?: string }; }

export default function OrdersPage() { return <AdminAuthGate active="orders">{(_, token) => <OrdersManager token={token} />}</AdminAuthGate>; }

function OrdersManager({ token }: { token: string }) { const [orders, setOrders] = useState<Order[]>([]); const [filter, setFilter] = useState('ALL'); const [error, setError] = useState('');
  useEffect(() => { fetch('/api/admin/orders', { headers: { Authorization: `Bearer ${token}` } }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); return result; }).then(setOrders).catch((reason) => setError(reason.message)); }, [token]);
  async function updateStatus(order: Order, status: string) { const response = await fetch('/api/admin/orders', { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ id: order.id, status }) }); const result = await response.json(); if (!response.ok) { setError(result.error); return; } setOrders((current) => current.map((item) => item.id === order.id ? { ...item, status } : item)); }
  const visible = orders.filter((order) => filter === 'ALL' || order.status === filter);
  return <><header className="admin-header"><div><div className="admin-kicker">Operations</div><h1>Orders</h1><p>Review customer orders and move them through the validated fulfilment flow.</p></div><ClipboardList size={30} color="var(--accent-purple)" /></header>{error && <div className="admin-error">{error}</div>}<section className="admin-panel"><div className="admin-panel-heading"><div><h2>Order queue</h2><p>{visible.length} of {orders.length} orders</p></div><select className="admin-filter" value={filter} onChange={(event) => setFilter(event.target.value)}><option>ALL</option><option>PENDING</option><option>PAID</option><option>SHIPPED</option><option>DELIVERED</option><option>CANCELLED</option></select></div>{visible.length ? <div className="admin-table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Delivery</th><th>Payment</th><th>Status</th><th>Total</th></tr></thead><tbody>{visible.map((order) => <tr key={order.id}><td><strong>{order.orderNumber}</strong><small>{new Date(order.createdAt).toLocaleString()}</small></td><td><strong>{order.customerName}</strong><small>{order.customerEmail}<br />{order.customerPhone}</small></td><td>{order.shippingAddress.addressLine1 || 'Address pending'}<small>{order.shippingAddress.city || ''}, {order.shippingAddress.district || ''}</small></td><td>{order.paymentMethod}</td><td><select className="admin-status-select" value={order.status} onChange={(event) => updateStatus(order, event.target.value)}><option>PENDING</option><option>PAID</option><option>SHIPPED</option><option>DELIVERED</option><option>CANCELLED</option></select></td><td>LKR {order.total.toLocaleString()}</td></tr>)}</tbody></table></div> : <div className="admin-empty">No orders found for this filter.</div>}</section></>;
}