'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ClipboardList } from 'lucide-react';
import AdminAuthGate from '@/components/AdminAuthGate';

interface Order { id: string; orderNumber: string; customerName: string; customerEmail: string; customerPhone: string; status: string; paymentStatus?: string; total: number; paymentMethod: string; createdAt: string; shippingAddress: { addressLine1?: string; city?: string; district?: string }; }

export default function OrdersPage() { return <AdminAuthGate active="orders">{(_, token) => <OrdersManager token={token} />}</AdminAuthGate>; }

function OrdersManager({ token }: { token: string }) { const [orders, setOrders] = useState<Order[]>([]); const [filter, setFilter] = useState('ALL'); const [reviewOnly, setReviewOnly] = useState(false); const [error, setError] = useState('');
  const nextStatuses: Record<string, string[]> = { CONFIRMED: ['PROCESSING', 'CANCELLED'], PROCESSING: ['PACKED', 'CANCELLED'], PACKED: ['SHIPPED'], SHIPPED: ['DELIVERED'] };
  useEffect(() => { fetch('/api/admin/orders', { headers: { Authorization: `Bearer ${token}` } }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); return result; }).then(setOrders).catch((reason) => setError(reason.message)); }, [token]);
  async function updateStatus(order: Order, status: string) { const response = await fetch('/api/admin/orders', { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ id: order.id, status }) }); const result = await response.json(); if (!response.ok) { setError(result.error); return; } setOrders((current) => current.map((item) => item.id === order.id ? { ...item, status } : item)); }
  async function confirmCodPayment(order: Order) { const response = await fetch(`/api/admin/orders/${order.id}/payment/confirm-cod`, { method: 'POST', headers: { Authorization: `Bearer ${token}` } }); const result = await response.json(); if (!response.ok) { setError(result.error); return; } setOrders((current) => current.map((item) => item.id === order.id ? { ...item, paymentStatus: 'PAID' } : item)); }
  const visible = orders.filter((order) => (filter === 'ALL' || order.status === filter) && (!reviewOnly || (order.paymentMethod === 'BANK_TRANSFER' && order.paymentStatus === 'PENDING')));
  return <><header className="admin-header"><div><div className="admin-kicker">Operations</div><h1>Orders</h1><p>Review customer orders and move them through the validated fulfilment flow.</p></div><ClipboardList size={30} color="var(--accent-purple)" /></header>{error && <div className="admin-error">{error}</div>}<section className="admin-panel"><div className="admin-panel-heading"><div><h2>Order queue</h2><p>{visible.length} of {orders.length} orders</p></div><div style={{ display: 'flex', gap: '.5rem', alignItems: 'center' }}><button className="admin-outline-button" onClick={() => setReviewOnly((current) => !current)}>{reviewOnly ? 'All orders' : 'Bank transfer reviews'}</button><select className="admin-filter" value={filter} onChange={(event) => setFilter(event.target.value)}><option>ALL</option><option>AWAITING_PAYMENT</option><option>CONFIRMED</option><option>PROCESSING</option><option>PACKED</option><option>SHIPPED</option><option>DELIVERED</option><option>CANCELLED</option></select></div></div>{visible.length ? <div className="admin-table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Delivery</th><th>Payment</th><th>Status</th><th>Total</th></tr></thead><tbody>{visible.map((order) => <tr key={order.id}><td><Link href={`/admin/orders/${order.id}`}><strong>{order.orderNumber}</strong></Link><small>{new Date(order.createdAt).toLocaleString()}</small></td><td><strong>{order.customerName}</strong><small>{order.customerEmail}<br />{order.customerPhone}</small></td><td>{order.shippingAddress.addressLine1 || 'Address pending'}<small>{order.shippingAddress.city || ''}, {order.shippingAddress.district || ''}</small></td><td>{order.paymentMethod}<small>{order.paymentStatus || 'PENDING'}</small>{order.paymentMethod === 'COD' && order.paymentStatus === 'UNPAID' && <button className="admin-inline-button" onClick={() => confirmCodPayment(order)}>Mark paid</button>}</td><td><select className="admin-status-select" value={order.status} onChange={(event) => updateStatus(order, event.target.value)}><option value={order.status}>{order.status}</option>{(nextStatuses[order.status] || []).map((status) => <option key={status} value={status}>{status}</option>)}</select></td><td>LKR {order.total.toLocaleString()}</td></tr>)}</tbody></table></div> : <div className="admin-empty">No orders found for this filter.</div>}</section></>;
}