'use client';

import { useEffect, useState } from 'react';
import { AlertTriangle, BarChart3, ClipboardList, Package, RefreshCw, Users } from 'lucide-react';
import AdminAuthGate from '@/components/AdminAuthGate';

interface DashboardData { metrics: { todayRevenue: number; todayOrders: number; totalProducts: number; totalCustomers: number; lowStock: number; bankTransferReviews: number }; statusCounts: Record<string, number>; recentOrders: { id: string; orderNumber: string; customerName: string; total: number; status: string; createdAt: string }[]; lowStock: { id: string; name: string; stockQty: number; price: number }[]; }

export default function AdminDashboardPage() { return <AdminAuthGate active="dashboard">{(_, token) => <Dashboard token={token} />}</AdminAuthGate>; }

function Dashboard({ token }: { token: string }) { const [data, setData] = useState<DashboardData | null>(null); const [error, setError] = useState(''); const load = () => fetch('/api/admin/dashboard', { headers: { Authorization: `Bearer ${token}` } }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); return result; }).then(setData).catch((reason) => setError(reason.message)); useEffect(() => { load(); }, [token]); return <><header className="admin-header"><div><div className="admin-kicker">Overview</div><h1>Store dashboard</h1><p>Live performance and operational alerts from your database.</p></div><button className="admin-refresh" onClick={load} title="Refresh dashboard"><RefreshCw size={18} /></button></header>{error && <div className="admin-error">{error}</div>}{data && <><div className="admin-metrics"><Metric icon={BarChart3} label="Today's revenue" value={`LKR ${data.metrics.todayRevenue.toLocaleString()}`} /><Metric icon={ClipboardList} label="Today's orders" value={String(data.metrics.todayOrders)} /><Metric icon={Package} label="Active products" value={String(data.metrics.totalProducts)} /><Metric icon={Users} label="Customers" value={String(data.metrics.totalCustomers)} /></div><div className="admin-panels"><section className="admin-panel"><div className="admin-panel-heading"><div><h2>Recent orders</h2><p>Latest customer activity</p></div><span>{Object.entries(data.statusCounts).map(([status, count]) => `${status}: ${count}`).join(' · ') || 'No orders'}</span></div>{data.recentOrders.length ? <div className="admin-table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Status</th><th>Total</th></tr></thead><tbody>{data.recentOrders.map((order) => <tr key={order.id}><td><strong>{order.orderNumber}</strong><small>{new Date(order.createdAt).toLocaleDateString()}</small></td><td>{order.customerName}</td><td><span className="admin-status">{order.status}</span></td><td>LKR {order.total.toLocaleString()}</td></tr>)}</tbody></table></div> : <div className="admin-empty">No orders found.</div>}</section><section className="admin-panel"><div className="admin-panel-heading"><div><h2>Low stock</h2><p>Products needing attention</p></div><span className="admin-alert-count">{data.metrics.lowStock}</span></div>{data.lowStock.length ? <div className="admin-stock-list">{data.lowStock.map((product) => <div key={product.id}><div><strong>{product.name}</strong><small>LKR {product.price.toLocaleString()}</small></div><b className={product.stockQty === 0 ? 'out' : ''}><AlertTriangle size={13} /> {product.stockQty} left</b></div>)}</div> : <div className="admin-empty">Stock levels look healthy.</div>}</section></div></>}</>; }
function Metric({ icon: Icon, label, value }: { icon: typeof BarChart3; label: string; value: string }) { return <div className="admin-metric"><Icon size={20} /><div><small>{label}</small><strong>{value}</strong></div></div>; }