'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { useStore } from '@/lib/store';

export default function SignupPage() {
  const router = useRouter(); const setUser = useStore((state) => state.setUser); const setAccessToken = useStore((state) => state.setAccessToken); const addToast = useStore((state) => state.addToast);
  const [form, setForm] = useState({ fullName: '', email: '', password: '', confirmPassword: '' }); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (form.password !== form.confirmPassword) { addToast('error', 'Passwords do not match.'); return; } setLoading(true); try { const response = await fetch('/api/auth/signup', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setUser(data.user); setAccessToken(data.accessToken); addToast('success', 'Account created successfully.'); router.push('/account'); } catch (error) { addToast('error', error instanceof Error ? error.message : 'Unable to create account.'); } finally { setLoading(false); } }
  return <div className="container" style={{ maxWidth: 520, padding: '5rem 1.25rem' }}><div style={{ background: 'var(--bg-white)', padding: '2.5rem', borderRadius: 'var(--radius-lg)', border: '1px solid var(--border-color)' }}><h1>Create your account</h1><p style={{ color: 'var(--text-secondary)', margin: '0.5rem 0 2rem' }}>Save your details and track every order.</p><form onSubmit={submit}><div className="form-group"><label className="form-label">Full name</label><input className="form-input" required value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })} /></div><div className="form-group"><label className="form-label">Email</label><input className="form-input" type="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></div><div className="form-group"><label className="form-label">Password</label><input className="form-input" type="password" minLength={8} required value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></div><div className="form-group"><label className="form-label">Confirm password</label><input className="form-input" type="password" minLength={8} required value={form.confirmPassword} onChange={(e) => setForm({ ...form, confirmPassword: e.target.value })} /></div><button className="btn-primary" disabled={loading} style={{ width: '100%', justifyContent: 'center' }}>{loading ? 'Creating account...' : 'Create account'}</button></form><p style={{ marginTop: '1.5rem', textAlign: 'center' }}>Already registered? <Link href="/login">Sign in</Link></p></div></div>;
}